import './globals.css';
import { Inter } from 'next/font/google';
import Nav from '@/components/nav';
import Provider from '@/components/provider';
import { authOptions } from './api/auth/[...nextauth]/route';
import { getServerSession } from 'next-auth/next';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'News Brief',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const email = (await getServerSession(authOptions))?.user?.email;

    return (
        <html lang="en">
            <body className={inter.className}>
                <Provider>
                    <main className="flow-root min-h-screen items-center space-x-10 space-y-10">
                        <Nav/>
                        {email && <p className="fixed bottom-2 right-4">{`Logged in as ${email}`}</p>}
                        {children}
                    </main>
                </Provider>
            </body>
        </html>
    )
}
