import './globals.css';
import { Inter } from 'next/font/google';
import Nav from '@/components/nav';
import Provider from '@/components/provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'News Brief',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Provider>
                <Nav/>
                <main className="flex min-h-screen flex-col items-center justify-between p-12">
                    {children}
                </main>
                </Provider>
            </body>
        </html>
    )
}
